<section class="global-content">
    <div class="img-container">
        <img src="public/images/couple.jpg" alt="Couple heureux au cinéma">
    </div>
    <div class="inscription">
        <h2 class="formTitle">Connexion Administrateur</h2>
        <form class="form"  method="post" action="index.php?action=homeAdmin">
            <input type="email" id="email"  name="email" placeholder="Enter your Email adress">
            <input type="password" id="password" name="password" placeholder="Enter your password">
            <button  type="submit" name="login-submit" class="btn-login"> Login </button>
        </form>
        <p id="pass-condition" >*Votre mot de passe doit contenir au moins 8 caractères, dont une lettre minuscule (a-z), une lettre majuscule (A-Z), un chiffre (0-9), un caractère spécial (!@#$%^&*). </p>  
    </div>
    <div class="img-container">
        <img src="public/images/boissonpopcorn.jpg" alt="Femme buvant une boisson au cinéma">
    </div>
</section>

