<section class="homeAdmin">
    <h2> Detail de la réservation</h2>
    <div class="table-wrapper">
        <table>
            <thead>
                <tr>
                    <th>N° de réservation</th>
                    <th>N° de film</th>
                    <th>N° de séance</th>
                    <th>Titre</th>
                    <th>Date</th>
                    <th>Heure</th>
                    <th>Quantité</th>
                </tr>
            </thead>
            <tbody>
            <?php foreach($bookings as $booking) : ?>
                <tr>
                    <td><?= htmlspecialchars($booking['booking_id']) ?></td>
                    <td><?= htmlspecialchars($booking['movie_id']) ?></td>
                    <td><?= htmlspecialchars($booking['session_id']) ?></td>
                    <td><?= htmlspecialchars($booking['title']) ?></td>
                    <td><?= htmlspecialchars($booking['date']) ?></td>
                    <td><?= htmlspecialchars(substr($booking['time'], 0, 5)) ?></td>
                    <td><?= htmlspecialchars($booking['quantity']) ?></td>
                </tr>
            <?php endforeach; ?> 
            </tbody>
        </table>
    </div>
</section>